config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    root "categories#index", as: "root"
    resources :users, only: [:index, :destroy]
    resources :categories
    resources :tags
    resources :books
    resources :reviews, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :requests, except: :new
  end
  resources :activities, only: [:create, :destroy]
  resources :users do
    resources :following, only: [:index]
    resources :followers, only: [:index]
  end
  resources :relationships, only: [:create, :destroy]
  resources :books, only: :show do
    resources :reviews, except: [:show, :new] do
      resources :comments
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  extend DatabaseQuery

  belongs_to :category

  has_many :reviews, dependent: :destroy
  has_many :book_users
  has_many :users, through: :book_users
  has_many :book_tags, dependent: :destroy
  has_many :tags, through: :book_tags

  has_attached_file :book_img, styles: {book_index: "100x100>>", book_show: "200x300>",
    book_show2: "370*500>"},
    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :book_img, content_type: /\Aimage\/.*\z/
  validates :title, presence: true, length: {maximum: 30}
  validates :description, presence: true
  validates :category, presence: true
  validates :author, presence: true

  scope :search, -> search {where "title LIKE ?", "#{search}%"}
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  layout "admin"
  before_action :logged_in_user, :verify_admin
  before_action :load_book, except: [:new, :index, :create]
  before_action :load_data, only: [:edit, :new]

  def index
    @books = Book.sort_by_title.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t "book.created_successfull"
      redirect_to admin_books_path
    else
      flash[:danger] = t "book.create_error"
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update_attributes book_params
      flash[:success] = t "book.updated_successfull"
      redirect_to admin_books_path
    else
      flash[:danger] = t "book.update_error"
      render :edit
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = t "book.deleted"
    else
      flash[:danger] = t "book.delete_error"
      redirect_to admin_books_path
    end
  end

  private
  def book_params
    params.require(:book).permit :title, :alias, :description, :author,
      :num_pages, :publish_date, :category_id, :book_img, tag_ids: []
  end

  def load_data
    @categories = Category.order :name
    @tags = Tag.all.order :name
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :load_book, only: :show

  def show
    get_reviews = @book.reviews
    @category_name = @book.category.name
    @build_review =  get_reviews.build
    @reviews = get_reviews.latest.includes(:user).paginate page: params[:page],
      per_page: Settings.per_page
    @avg_rating = get_reviews.average(:rate)
      .present? ? get_reviews.average(:rate) : 0
  end

  private
  def load_book
    @book = Book.find_by id: params[:id]
    if @book.nil?
      flash[:danger] = t "book_nil"
      redirect_to root_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def rate_value value
    @book.reviews.count_rate value
  end
end

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book], html: {multipart: true} do |f| %>

  <%= render "shared/error_messages", object: @book %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :alias %>
  <%= f.text_field :alias %>

  <%= f.file_field :book_img %>

  <%= f.label :category %>
  <%= f.collection_select :category_id, @categories, :id, :name,
    include_blank: true %>

  <%= f.label :description %>
  <%= f.text_area :description %><br>

  <div class="field">
    <%= f.label :tags %><br />
    <%= f.collection_check_boxes :tag_ids, @tags, :id, :name do |b| %>
      <div class="collection-check-box">
        <%= b.check_box %>
        <%= b.label %>
      </div>
    <% end %>
  </div>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :publish_date %>
  <%= f.datetime_field :publish_date %>

  <%= f.submit %>
<% end %>

app/views/admin/books/edit.html.erb
<div id="content">
  <h2><%= t "book.edit_title" %></h2>
  <%= render "form" %>
</div>

app/views/admin/books/index.html.erb
<div id="content">
  <h2> <%= t "book.manage" %> </h2>
  <table>
    <thead>
      <tr>
        <th><%= t "book.index" %></th>
        <th><%= t "book.image" %></th>
        <th><%= t "book.title" %></th>
        <th><%= t "book.review" %></th>
        <th><%= t "edit" %></th>
        <th><%= t "book.delete" %></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each.with_index do |book, index| %>
        <tr>
          <td><% params[:page] ||= "1" %>
            <%= index_for params[:page], index, Settings.per_page %>
          </td>
          <td><%= link_to image_tag book.book_img.url(:book_index) %></td>
          <td><%= book.title %></td>
          <td><%= book.reviews.count %></td>
          <td>
            <%= link_to t("edit"), edit_admin_book_path(book),
              class: "edit" %>
          </td>
          <td>
            <%= link_to t("category.delete"), admin_book_path(book),
              method: :delete, data: {confirm: t("confirm_delete")},
              class: "delete" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/books/new.html.erb
<div id="content">
  <h2><%= t "book.new" %></h2>
  <%= render "form" %>
</div>