config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    root "categories#index", as: "root"
    resources :users, only: [:index, :destroy]
    resources :categories
    resources :tags
    resources :books
    resources :reviews, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :requests, except: :new
  end
  resources :activities, only: [:create, :destroy]
  resources :users do
    resources :following, only: [:index]
    resources :followers, only: [:index]
  end
  resources :relationships, only: [:create, :destroy]
  resources :books, only: :show do
    resources :reviews, except: [:show, :new] do
      resources :comments
    end
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  extend DatabaseQuery
  has_many :book_tags, dependent: :destroy
  has_many :books, through: :book_tags

  validates :name, presence: true, uniqueness: {case_sensitive: true}
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  layout "admin"
  before_action :logged_in_user, :verify_admin
  before_action :load_tag, except: [:new, :index, :create]

  def index
    @tags = Tag.sort_by_name.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new tag_params
    if @tag.save
      flash[:success] = t "tag.created_successfull"
      redirect_to admin_tags_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @tag.update_attributes tag_params
      flash[:success] = t "tag.updated"
    else
      flash[:danger] = t "tag.update_error"
      render :edit
    end
    redirect_to admin_tags_path
  end

  def destroy
    if @tag.destroy
      flash[:success] = t "tag.deleted"
    else
      flash[:danger] = t "tag.delete_error"
    end
    redirect_to admin_tags_path
  end

  private
  def tag_params
    params.require(:tag).permit :name
  end

  def load_tag
    @tag = Tag.find_by id: params[:id]
    if @tag.nil?
      flash[:notice] = t "tag.not_found"
      redirect_to admin_root_path
    end
  end
end

app/views/admin/tags/_form.html.erb
<%= form_for [:admin, @tag] do |f| %>
  <%= render "shared/error_messages", object: @tag %>
  <%= f.label :title %>
  <%= f.text_field :name %><br><br>
  <%= f.submit %>
<% end %>

app/views/admin/tags/edit.html.erb
<div id="content">
  <h2><%= t "tag.edit_title" %></h2>
  <%= render "form" %>
</div>

app/views/admin/tags/index.html.erb
<div id="content">
  <h2><%= t "manage_tags" %></h2>
  <table>
    <thead>
      <tr>
        <th><%= t "tags" %></th>
        <th><%= t "tag.edit" %></th>
        <th><%= t "tag.delete" %></th>
      </tr>
    </thead>
    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td>
            <%= link_to t("edit"), edit_admin_tag_path(tag),
              class: "edit" %>
          </td>
          <td>
            <%= link_to t("tag.delete"), admin_tag_path(tag),
              method: :delete, data: {confirm: t("confirm_delete")},
              class: "delete" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/tags/new.html.erb
<div id="content">
  <h2><%= t "tag.new" %></h2>
  <%= render "form" %>
</div>