config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    root "categories#index", as: "root"
    resources :users, only: [:index, :destroy]
    resources :categories
    resources :tags
    resources :books
    resources :reviews, only: [:index, :destroy]
    resources :comments, only: [:index, :destroy]
    resources :requests, except: :new
  end
  resources :activities, only: [:create, :destroy]
  resources :users do
    resources :following, only: [:index]
    resources :followers, only: [:index]
  end
  resources :relationships, only: [:create, :destroy]
  resources :books, only: :show do
    resources :reviews, except: [:show, :new] do
      resources :comments
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  extend DatabaseQuery
  validates :name, uniqueness: {case_sensitive: true}

  has_many :books, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  layout "admin"
  before_action :logged_in_user
  before_action :verify_admin
  before_action :load_category, except: [:new, :index, :create]

  def index
    @categories = Category.sort_by_name.paginate page: params[:page],
      per_page: Settings.per_page
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "category.created_successfull"
      redirect_to admin_root_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "category.updated"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "category.deleted"
      redirect_to admin_categories_path
    else
      flash[:danger] = t "category.delete_error"
      redirect_to admin_root_path
    end
  end

  private
  def category_params
    params.require(:category).permit :name, :alias
  end

  def load_category
    @category = Category.find_by id: params[:id]
    if @category.nil?
      flash[:notice] = t "category.not_found"
      redirect_to admin_root_path
    end
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: @category %>
  <%= f.label :title %>
  <%= f.text_field :name %><br><br>
  <%= f.submit %>
<% end %>

app/views/admin/categories/edit.html.erb
<div id="content">
  <h2><%= t "category.edit_title" %></h2>
  <%= render "form" %>
</div>

app/views/admin/categories/index.html.erb
<div id="content">
  <h2><%= t "manage_categories" %></h2>
  <table>
    <thead>
      <tr>
        <th><%= t "categories" %></th>
        <th><%= t "category.edit" %></th>
        <th><%= t "category.delete" %></th>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td><%= category.name %></td>
          <td>
            <%= link_to t("edit"), edit_admin_category_path(category),
              class: "edit" %>
          </td>
          <td>
            <%= link_to t("category.delete"), admin_category_path(category),
              method: :delete, data: {confirm: t("confirm_delete")},
              class: "delete" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/categories/new.html.erb
<div id="content">
  <h2><%= t "category.new" %></h2>
  <%= render "form" %>
</div>